name = "LSJMining"
uuid = "43354e92-6fc2-4cf2-af8b-a72a4ebba07f"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LexiconMining = "d7cc8c4b-a12f-4850-86db-026797cdfce2"
PolytonicGreek = "72b824a7-2b4a-40fa-944c-ac4f345dc63a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
DocStringExtensions = "0.8"
Documenter = "0.27"
LexiconMining = "0.2.1"
PolytonicGreek = "0.15"
