prefixdict = Dict(
PG.nfkc("ἀμ") => PG.nfkc("ἀμ"),
PG.nfkc("ἀν") => PG.nfkc("ἀν"),
PG.nfkc("ἀνα") => PG.nfkc("ἀνα"),
PG.nfkc("ἀνεπ") => PG.nfkc("ἀν#επ"),

PG.nfkc("ἀνθ") => PG.nfkc("ἀνθ"),
PG.nfkc("ἀνθυπ") => PG.nfkc("ἀνθ#υπ"),
PG.nfkc("ἀνθυπο") => PG.nfkc("ἀνθ#υπο"),
PG.nfkc("ἀντ") => PG.nfkc("ἀντ"),
PG.nfkc("ἀνταπ") => PG.nfkc("ἀντ#απ"),
PG.nfkc("ἀνταπο") => PG.nfkc("ἀντ#απο"),
PG.nfkc("ἀντεν") => PG.nfkc("ἀντ#εν"),
PG.nfkc("ἀντεμ") => PG.nfkc("ἀντ#εμ"),
PG.nfkc("ἀντεγ") => PG.nfkc("ἀντ#εγ"),
PG.nfkc("ἀντεισ") => PG.nfkc("ἀντ#εισ"),
PG.nfkc("ἀντεπι") => PG.nfkc("ἀντ#επι"),
PG.nfkc("ἀντι") => PG.nfkc("ἀντι"),
PG.nfkc("ἀντιδια") => PG.nfkc("ἀντι#δια"),
PG.nfkc("ἀντικατα") => PG.nfkc("ἀντι#κατα"),
PG.nfkc("ἀντικατ") => PG.nfkc("ἀντι#κατ"),
PG.nfkc("ἀντιπαρα") => PG.nfkc("ἀντι#παρα"),


PG.nfkc("ἀπ") => PG.nfkc("ἀπ"),
PG.nfkc("ἀπεν") => PG.nfkc("ἀπ#εν"),
PG.nfkc("ἀπεμ") => PG.nfkc("ἀπ#εμ"),
PG.nfkc("ἀπο") => PG.nfkc("ἀπο"),
PG.nfkc("ἀποδια") => PG.nfkc("ἀπο#δια"),
PG.nfkc("ἀφ") => PG.nfkc("ἀφ"),

PG.nfkc("δι") => PG.nfkc("δι"),
PG.nfkc("δια") => PG.nfkc("δια"),
PG.nfkc("διεν") => PG.nfkc("δι#εν"),
PG.nfkc("διεμ") => PG.nfkc("δι#εμ"),

PG.nfkc("εἰσ") => PG.nfkc("εἰσ"),

PG.nfkc("ἐκ") => PG.nfkc("ἐκ"),
PG.nfkc("ἐξ") => PG.nfkc("ἐξ"),
PG.nfkc("ἐξανα") => PG.nfkc("ἐξ#ανα"),

PG.nfkc("ἐγ") => PG.nfkc("ἐγ"),
PG.nfkc("ἐγκατα") => PG.nfkc("ἐγ#κατα"),
PG.nfkc("ἐμ") => PG.nfkc("ἐμ"),
PG.nfkc("ἐν") => PG.nfkc("ἐν"),
PG.nfkc("ἐναπο") => PG.nfkc("ἐν#απο"),
PG.nfkc("ἐμπερι") => PG.nfkc("ἐμ#περι"),

PG.nfkc("ἐπεισ") => PG.nfkc("ἐπ#εισ"),
PG.nfkc("ἐπ") => PG.nfkc("ἐπ"),
PG.nfkc("ἐπι") => PG.nfkc("ἐπι"),
PG.nfkc("ἐπιδια") => PG.nfkc("ἐπι#δια"),
PG.nfkc("ἐφ") => PG.nfkc("ἐφ"),

PG.nfkc("καθ") => PG.nfkc("καθ"),
PG.nfkc("καθυπο") => PG.nfkc("καθ#υπο"),
PG.nfkc("κατα") => PG.nfkc("κατα"),
PG.nfkc("κατ") => PG.nfkc("κατ"),

PG.nfkc("μεθ") => PG.nfkc("μεθ"),
PG.nfkc("μετ") => PG.nfkc("μετ"),
PG.nfkc("μετα") => PG.nfkc("μετα"),
PG.nfkc("μετεγ") => PG.nfkc("μετ#εγ"),
PG.nfkc("μετεν") => PG.nfkc("μετ#εν"),

PG.nfkc("παρ") => PG.nfkc("παρ"),
PG.nfkc("παρα") => PG.nfkc("παρα"),
PG.nfkc("παρεισ") => PG.nfkc("παρ#εισ"),
PG.nfkc("παρεκ") => PG.nfkc("παρ#εκ"),
PG.nfkc("παρεν") => PG.nfkc("παρ#εν"),
PG.nfkc("παρεμ") => PG.nfkc("παρ#εμ"),
PG.nfkc("παρεπι") => PG.nfkc("παρ#επι"),

PG.nfkc("περι") => PG.nfkc("περι"),

PG.nfkc("προαπο") => PG.nfkc("προ#απο"),
PG.nfkc("προ") => PG.nfkc("προ"),
PG.nfkc("προανα") => PG.nfkc("προ#ανα"),
PG.nfkc("προδια") => PG.nfkc("προ#δια"),
PG.nfkc("προεγ") => PG.nfkc("προ#εγ"),
PG.nfkc("προεισ") => PG.nfkc("προ#εισ"),
PG.nfkc("προεκ") => PG.nfkc("προ#εκ"),
PG.nfkc("προεξ") => PG.nfkc("προ#εξ"),
PG.nfkc("προεν") => PG.nfkc("προ#εν"),
PG.nfkc("προεμ") => PG.nfkc("προ#εμ"),
PG.nfkc("προεπι") => PG.nfkc("προ#επι"),
PG.nfkc("προκατα") => PG.nfkc("προ#κατα"),
PG.nfkc("προϋπο") => PG.nfkc("προ#ϋπο"),

PG.nfkc("προσ") => PG.nfkc("προσ"),
PG.nfkc("προσανα") => PG.nfkc("προσ#ανα"),
PG.nfkc("προσαντι") => PG.nfkc("προσ#αντι"),
PG.nfkc("προσαντεπι") => PG.nfkc("προσ#αντ#επι"),
PG.nfkc("προσαπο") => PG.nfkc("προσ#απο"),
PG.nfkc("προσδια") => PG.nfkc("προσ#δια"),
PG.nfkc("προσεν") => PG.nfkc("προσ#εν"),
PG.nfkc("προσεπι") => PG.nfkc("προσ#επι"),
PG.nfkc("προσκατα") => PG.nfkc("προσ#κατα"),
PG.nfkc("προσπαρα") => PG.nfkc("προσ#παρα"),
PG.nfkc("προσυπεν") => PG.nfkc("προσ#υπ#εν"),
PG.nfkc("προσυπεμ") => PG.nfkc("προσ#υπ#εμ"),
PG.nfkc("προσυπο") => PG.nfkc("προσ#υπο"),


PG.nfkc("συ") => PG.nfkc("συ"),
PG.nfkc("συν") => PG.nfkc("συν"),
PG.nfkc("συνανα") => PG.nfkc("συν#ανα"),
PG.nfkc("συναπο") => PG.nfkc("συν#απο"),
PG.nfkc("συνεν") => PG.nfkc("συν#εν"),
PG.nfkc("συνεμ") => PG.nfkc("συν#εμ"),
PG.nfkc("συγ") => PG.nfkc("συγ"),
PG.nfkc("συγκατα") => PG.nfkc("συγ#κατα"),
PG.nfkc("συλ") => PG.nfkc("συλ"),
PG.nfkc("συμ") => PG.nfkc("συμ"),
PG.nfkc("συμπαρα") => PG.nfkc("συμ#παρα"),
PG.nfkc("συμπαρ") => PG.nfkc("συμ#παρ"),
PG.nfkc("συμπερι") => PG.nfkc("συμ#περι"),
PG.nfkc("συναντι") => PG.nfkc("συν#αντι"),
PG.nfkc("συναπο") => PG.nfkc("συν#απο"),
PG.nfkc("συνδια") => PG.nfkc("συν#δια"),
PG.nfkc("συνεισ") => PG.nfkc("συν#εισ"),
PG.nfkc("συνεκ") => PG.nfkc("συν#εκ"),
PG.nfkc("συνεν") => PG.nfkc("συν#εν"),
PG.nfkc("συνεγ") => PG.nfkc("συν#εγ"),
PG.nfkc("συνεπι") => PG.nfkc("συν#επι"),
PG.nfkc("συνυπο") => PG.nfkc("συν#υπο"),
PG.nfkc("συρ") => PG.nfkc("συρ"),

PG.nfkc("ὑπ") => PG.nfkc("ὑπ"),
PG.nfkc("ὑπεκ") => PG.nfkc("ὑπ#εκ"),
PG.nfkc("ὑπεξ") => PG.nfkc("ὑπ#εξ"),
PG.nfkc("ὑπεν") => PG.nfkc("ὑπ#εν"),
PG.nfkc("ὑπεμ") => PG.nfkc("ὑπ#εμ"),
PG.nfkc("ὑπερ") => PG.nfkc("ὑπερ"),
PG.nfkc("ὑπο") => PG.nfkc("ὑπο"),
PG.nfkc("ὑποδια") => PG.nfkc("ὑπο#δια"),
PG.nfkc("ὑποκατα") => PG.nfkc("ὑπο#κατα)"),
PG.nfkc("ὑφ") => PG.nfkc("ὑφ")
)
