prefixdict = Dict(
PG.nfkc("ἀμ") => PG.nfkc("ἀμ"),
PG.nfkc("ἀμφ") => PG.nfkc("ἀμφ"),
PG.nfkc("ἀμφι") => PG.nfkc("ἀμφι"),

PG.nfkc("ἀν") => PG.nfkc("ἀν"),
PG.nfkc("ἀνα") => PG.nfkc("ἀνα"),
PG.nfkc("ἀνεπ") => PG.nfkc("ἀν#επ"),

PG.nfkc("ἀνθ") => PG.nfkc("ἀνθ"),
PG.nfkc("ἀνθυπ") => PG.nfkc("ἀνθ#υπ"),
PG.nfkc("ἀνθυπο") => PG.nfkc("ἀνθ#υπο"),
PG.nfkc("ἀντ") => PG.nfkc("ἀντ"),
PG.nfkc("ἀνταπ") => PG.nfkc("ἀντ#απ"),
PG.nfkc("ἀνταπο") => PG.nfkc("ἀντ#απο"),
PG.nfkc("ἀντεν") => PG.nfkc("ἀντ#εν"),
PG.nfkc("ἀντεμ") => PG.nfkc("ἀντ#εμ"),
PG.nfkc("ἀντεγ") => PG.nfkc("ἀντ#εγ"),
PG.nfkc("ἀντεισ") => PG.nfkc("ἀντ#εισ"),
PG.nfkc("ἀντεπι") => PG.nfkc("ἀντ#επι"),
PG.nfkc("ἀντι") => PG.nfkc("ἀντι"),
PG.nfkc("ἀντιδια") => PG.nfkc("ἀντι#δια"),
PG.nfkc("ἀντικατα") => PG.nfkc("ἀντι#κατα"),
PG.nfkc("ἀντικατ") => PG.nfkc("ἀντι#κατ"),
PG.nfkc("ἀντιπαρα") => PG.nfkc("ἀντι#παρα"),
PG.nfkc("ἀνταν") => PG.nfkc("ἀντ#αν"),
PG.nfkc("ἀνταφ") => PG.nfkc("ἀντ#αφ"),
PG.nfkc("ἀντεκ") => PG.nfkc("ἀντ#εκ"),
PG.nfkc("ἀντεφ") => PG.nfkc("ἀντ#εφ"),
PG.nfkc("ἀντεπαφ") => PG.nfkc("ἀντ#επ#αφ"),
PG.nfkc("ἀντικαθ") => PG.nfkc("ἀντι#καθ"),
PG.nfkc("ἀντιμεθ") => PG.nfkc("ἀντι#μεθ"),
PG.nfkc("ἀντιπαρ") => PG.nfkc("ἀντι#παρ"),
PG.nfkc("ἀντιπρο") => PG.nfkc("ἀντι#προ"),


PG.nfkc("ἀπ") => PG.nfkc("ἀπ"),
PG.nfkc("ἀπαν") => PG.nfkc("ἀπ#αν"),
PG.nfkc("ἀπεκ") => PG.nfkc("ἀπ#εκ"),
PG.nfkc("ἀπεν") => PG.nfkc("ἀπ#εν"),
PG.nfkc("ἀπεμ") => PG.nfkc("ἀπ#εμ"),
PG.nfkc("ἀπο") => PG.nfkc("ἀπο"),
PG.nfkc("ἀποδια") => PG.nfkc("ἀπο#δια"),
PG.nfkc("ἀφ") => PG.nfkc("ἀφ"),
PG.nfkc("ἀποκαθ") => PG.nfkc("ἀπο#καθ"),
PG.nfkc("ἀπομεθ") => PG.nfkc("ἀπο#μεθ"),
PG.nfkc("ἀποσυν") => PG.nfkc("ἀπο#συν"),
PG.nfkc("ἀποκατα") => PG.nfkc("ἀπο#κατα"),


PG.nfkc("δι") => PG.nfkc("δι"),
PG.nfkc("δια") => PG.nfkc("δια"),
PG.nfkc("διαμεθ") => PG.nfkc("δια#μεθ"),
PG.nfkc("διαπαρ") => PG.nfkc("δια#παρ"),
PG.nfkc("διασυν") => PG.nfkc("δια#συν"),
PG.nfkc("διυπερ") => PG.nfkc("δι#υπερ"),
PG.nfkc("διαν") => PG.nfkc("δι#αν"),
PG.nfkc("διαφ") => PG.nfkc("δι#αφ"),
PG.nfkc("διυφ") => PG.nfkc("δι#υφ"),
PG.nfkc("διαπο") => PG.nfkc("δια#απο"),
PG.nfkc("διεκ") => PG.nfkc("δι#εκ"),
PG.nfkc("διεξ") => PG.nfkc("δι#εξ"),
PG.nfkc("διεν") => PG.nfkc("δι#εν"),
PG.nfkc("διεμ") => PG.nfkc("δι#εμ"),
PG.nfkc("διαπαρα") => PG.nfkc("δια#παρα"),

PG.nfkc("εἰσ") => PG.nfkc("εἰσ"),
PG.nfkc("εἰσαφ") => PG.nfkc("εἰσ#αφ"),
PG.nfkc("εἰσεν") => PG.nfkc("εἰσ#εν"),
PG.nfkc("εἰσκατα") => PG.nfkc("εἰσ#κατα"),


PG.nfkc("ἐκ") => PG.nfkc("ἐκ"),
PG.nfkc("ἐξ") => PG.nfkc("ἐξ"),
PG.nfkc("ἐξανα") => PG.nfkc("ἐξ#ανα"),
PG.nfkc("ἐξαν") => PG.nfkc("ἐξ#αν"),
PG.nfkc("ἐξαφ") => PG.nfkc("ἐξαφ"),
PG.nfkc("ἐξεφ") => PG.nfkc("ἐξ#εφ"),
PG.nfkc("ἐξυπαν") => PG.nfkc("ἐξ#υπ#αν"),

PG.nfkc("ἐγ") => PG.nfkc("ἐγ"),
PG.nfkc("ἐγκατα") => PG.nfkc("ἐγ#κατα"),
PG.nfkc("ἐγκαθ") => PG.nfkc("ἐγ#καθ"),
PG.nfkc("εἰσαπο") => PG.nfkc("εἰσ#απο"),
PG.nfkc("εἰσκαθ") => PG.nfkc("εἰσ#καθ"),
PG.nfkc("ἐμ") => PG.nfkc("ἐμ"),
PG.nfkc("ἐν") => PG.nfkc("ἐν"),
PG.nfkc("ἐναπο") => PG.nfkc("ἐν#απο"),
PG.nfkc("ἐναφ") => PG.nfkc("ἐν#αφ"),
PG.nfkc("ἐμπερι") => PG.nfkc("ἐμ#περι"),

PG.nfkc("ἐπ") => PG.nfkc("ἐπ"),
PG.nfkc("ἐπι") => PG.nfkc("ἐπι"),
PG.nfkc("ἐπαν") => PG.nfkc("ἐπ#αν"),
PG.nfkc("ἐπανα") => PG.nfkc("ἐπ#ανα"),
PG.nfkc("ἐπαπο") => PG.nfkc("ἐπ#απο"),
PG.nfkc("ἐπαφ") => PG.nfkc("ἐπ#αφ"),
PG.nfkc("ἐπιδι") => PG.nfkc("ἐπι#δι"),
PG.nfkc("ἐπεισ") => PG.nfkc("ἐπ#εισ"),
PG.nfkc("ἐπεκ") => PG.nfkc("ἐπ#εκ"),
PG.nfkc("ἐπεν") => PG.nfkc("ἐπ#εν"),
PG.nfkc("ἐπιδια") => PG.nfkc("ἐπι#δια"),
PG.nfkc("ἐφ") => PG.nfkc("ἐφ"),
PG.nfkc("ἐπεξαν") => PG.nfkc("ἐπ#εξ#αν"),
PG.nfkc("ἐπικαθ") => PG.nfkc("ἐπι#καθ"),
PG.nfkc("ἐπισυν") => PG.nfkc("ἐπι#συν"),
PG.nfkc("ἐπιπροσ") => PG.nfkc("ἐπι#προσ"),


PG.nfkc("καθ") => PG.nfkc("καθ"),
PG.nfkc("καθυπο") => PG.nfkc("καθ#υπο"),
PG.nfkc("καθυφ") => PG.nfkc("καθ#υφ"),
PG.nfkc("κατα") => PG.nfkc("κατα"),
PG.nfkc("κατ") => PG.nfkc("κατ"),
PG.nfkc("καταφ") => PG.nfkc("κατ#αφ"),
PG.nfkc("καταπρο") => PG.nfkc("κατα#προ"),

PG.nfkc("μεθ") => PG.nfkc("μεθ"),
PG.nfkc("μετ") => PG.nfkc("μετ"),
PG.nfkc("μετα") => PG.nfkc("μετα"),
PG.nfkc("μεταν") => PG.nfkc("μετ#αν"),
PG.nfkc("μετεκ") => PG.nfkc("μετ#εκ"),
PG.nfkc("μετεγ") => PG.nfkc("μετ#εγ"),
PG.nfkc("μετεν") => PG.nfkc("μετ#εν"),
PG.nfkc("μετασυν") => PG.nfkc("μετα#συν"),
PG.nfkc("μεταπαρα") => PG.nfkc("μετα#παρα"),

PG.nfkc("παρ") => PG.nfkc("παρ"),
PG.nfkc("παρα") => PG.nfkc("παρα"),
PG.nfkc("παρανα") => PG.nfkc("παρ#ανα"),
PG.nfkc("παραν") => PG.nfkc("παρ#αν"),
PG.nfkc("παραφ") => PG.nfkc("παρ#αφ"),
PG.nfkc("παρεξ") => PG.nfkc("παρ#εξ"),
PG.nfkc("παρυφ") => PG.nfkc("παρ#υφ"),
PG.nfkc("παρεισ") => PG.nfkc("παρ#εισ"),
PG.nfkc("παρεκ") => PG.nfkc("παρ#εκ"),
PG.nfkc("παρεν") => PG.nfkc("παρ#εν"),
PG.nfkc("παρεμ") => PG.nfkc("παρ#εμ"),
PG.nfkc("παρεπι") => PG.nfkc("παρ#επι"),
PG.nfkc("παρακαθ") => PG.nfkc("παρα#καθ"),
PG.nfkc("παραμεθ") => PG.nfkc("παρα#μεθ"),
PG.nfkc("παρακατα") => PG.nfkc("παρα#κατα"),

PG.nfkc("περι") => PG.nfkc("περι"),
PG.nfkc("περιαν") => PG.nfkc("περι#αν"),
PG.nfkc("ποτι") => PG.nfkc("ποτι"),

PG.nfkc("προ") => PG.nfkc("προ"),
PG.nfkc("προανα") => PG.nfkc("προ#ανα"),
PG.nfkc("προαν") => PG.nfkc("πρ#οαν"),
PG.nfkc("προαπο") => PG.nfkc("προ#απο"),
PG.nfkc("προαφ") => PG.nfkc("προ#αφ"),
PG.nfkc("προδι") => PG.nfkc("προ#δι"),
PG.nfkc("προδια") => PG.nfkc("προ#δια"),
PG.nfkc("προεγ") => PG.nfkc("προ#εγ"),
PG.nfkc("προεισ") => PG.nfkc("προ#εισ"),
PG.nfkc("προεκ") => PG.nfkc("προ#εκ"),
PG.nfkc("προεξ") => PG.nfkc("προ#εξ"),
PG.nfkc("προεν") => PG.nfkc("προ#εν"),
PG.nfkc("προεμ") => PG.nfkc("προ#εμ"),
PG.nfkc("προεπι") => PG.nfkc("προ#επι"),
PG.nfkc("προεφ") => PG.nfkc("προ#εφ"),
PG.nfkc("προκατα") => PG.nfkc("προ#κατα"),
PG.nfkc("προκατανα") => PG.nfkc("προ#κατ#ανα"),
PG.nfkc("προϋπο") => PG.nfkc("προ#ϋπο"),
PG.nfkc("προκαθ") => PG.nfkc("προ#καθ"),
PG.nfkc("προμεθ") => PG.nfkc("προ#μεθ"),
PG.nfkc("προσυν") => PG.nfkc("προ#συν"),
PG.nfkc("προεπαφ") => PG.nfkc("προ#επ#αφ"),
PG.nfkc("προπαρα") => PG.nfkc("προ#παρα"),
PG.nfkc("προδιασυν") => PG.nfkc("προ#δια#συν"),


PG.nfkc("προσ") => PG.nfkc("προσ"),
PG.nfkc("προσαν") => PG.nfkc("προσ#αν"),
PG.nfkc("προσαφ") => PG.nfkc("προσ#αφ"),
PG.nfkc("προσδι") => PG.nfkc("προσ#δι"),
PG.nfkc("προσεκ") => PG.nfkc("προσ#εκ"),
PG.nfkc("προσεξ") => PG.nfkc("προσ#εξ"),
PG.nfkc("προσανα") => PG.nfkc("προσ#ανα"),
PG.nfkc("προσαντι") => PG.nfkc("προσ#αντι"),
PG.nfkc("προσαντεπι") => PG.nfkc("προσ#αντ#επι"),
PG.nfkc("προσαπο") => PG.nfkc("προσ#απο"),
PG.nfkc("προσδια") => PG.nfkc("προσ#δια"),
PG.nfkc("προσεν") => PG.nfkc("προσ#εν"),
PG.nfkc("προσκαθ") => PG.nfkc("προσ#καθ"),
PG.nfkc("προσσυν") => PG.nfkc("προσ#συν"),
PG.nfkc("προσμετα") => PG.nfkc("προσ#μετα"),
PG.nfkc("προσανταπο") => PG.nfkc("προσ#αντ#απο"),


PG.nfkc("προσεπι") => PG.nfkc("προσ#επι"),
PG.nfkc("προσκατα") => PG.nfkc("προσ#κατα"),
PG.nfkc("προσπαρα") => PG.nfkc("προσ#παρα"),
PG.nfkc("προσυπεν") => PG.nfkc("προσ#υπ#εν"),
PG.nfkc("προσυπεμ") => PG.nfkc("προσ#υπ#εμ"),
PG.nfkc("προσυπο") => PG.nfkc("προσ#υπο"),


PG.nfkc("συ") => PG.nfkc("συ"),
PG.nfkc("συν") => PG.nfkc("συν"),
PG.nfkc("συνανα") => PG.nfkc("συν#ανα"),
PG.nfkc("συναπο") => PG.nfkc("συν#απο"),
PG.nfkc("συναν") => PG.nfkc("συν#αν"),
PG.nfkc("συναφ") => PG.nfkc("συν#αφ"),
PG.nfkc("συνεφ") => PG.nfkc("συν#εφ"),
PG.nfkc("συνυφ") => PG.nfkc("συν#υφ"),
PG.nfkc("συνεν") => PG.nfkc("συν#εν"),
PG.nfkc("συνεμ") => PG.nfkc("συν#εμ"),
PG.nfkc("συγ") => PG.nfkc("συγ"),
PG.nfkc("συγκατα") => PG.nfkc("συγ#κατα"),
PG.nfkc("συλ") => PG.nfkc("συλ"),
PG.nfkc("συμ") => PG.nfkc("συμ"),
PG.nfkc("συμπαρα") => PG.nfkc("συμ#παρα"),
PG.nfkc("συμπαρ") => PG.nfkc("συμ#παρ"),
PG.nfkc("συμπερι") => PG.nfkc("συμ#περι"),
PG.nfkc("συναντι") => PG.nfkc("συν#αντι"),
PG.nfkc("συναπο") => PG.nfkc("συν#απο"),
PG.nfkc("συνδια") => PG.nfkc("συν#δια"),
PG.nfkc("συνεισ") => PG.nfkc("συν#εισ"),
PG.nfkc("συνεκ") => PG.nfkc("συν#εκ"),
PG.nfkc("συνεν") => PG.nfkc("συν#εν"),
PG.nfkc("συνεγ") => PG.nfkc("συν#εγ"),
PG.nfkc("συνεπι") => PG.nfkc("συν#επι"),
PG.nfkc("συνυπο") => PG.nfkc("συν#υπο"),
PG.nfkc("συρ") => PG.nfkc("συρ"),
PG.nfkc("συγκαθ") => PG.nfkc("συγ#καθ"),
PG.nfkc("συμμεθ") => PG.nfkc("συμ#μεθ"),
PG.nfkc("συμπρο") => PG.nfkc("συμ#προ"),
PG.nfkc("συμμετα") => PG.nfkc("συμ#μετα"),
PG.nfkc("συμπροσ") => PG.nfkc("συμ#προσ"),
PG.nfkc("συνεξαν") => PG.nfkc("συν#εξ#αν"),
PG.nfkc("συνεπαφ") => PG.nfkc("συν#επ#αφ"),
PG.nfkc("συναποκαθ") => PG.nfkc("συν#απο#καθ"),


PG.nfkc("ὑπερ") => PG.nfkc("ὑπερ"),
PG.nfkc("ὑπεραπο") => PG.nfkc("ὑπερ#απο"),
PG.nfkc("ὑπερκαθ") => PG.nfkc("ὑπερ#καθ"),


PG.nfkc("ὑπ") => PG.nfkc("ὑπ"),
PG.nfkc("ὑπαν") => PG.nfkc("ὑπ#αν"),
PG.nfkc("ὑπεκ") => PG.nfkc("ὑπ#εκ"),
PG.nfkc("ὑπεξ") => PG.nfkc("ὑπ#εξ"),
PG.nfkc("ὑπεν") => PG.nfkc("ὑπ#εν"),
PG.nfkc("ὑπεμ") => PG.nfkc("ὑπ#εμ"),
PG.nfkc("ὑπο") => PG.nfkc("ὑπο"),
PG.nfkc("ὑποδια") => PG.nfkc("ὑπο#δια"),
PG.nfkc("ὑποκατα") => PG.nfkc("ὑπο#κατα)"),
PG.nfkc("ὑποπερι") => PG.nfkc("ὑπο#περι"),
PG.nfkc("ὑφ") => PG.nfkc("ὑφ"),
PG.nfkc("ὑποκαθ") => PG.nfkc("ὑπο#καθ"),
PG.nfkc("ὑποπρο") => PG.nfkc("ὑπο#προ"),
)

